name: reviewdog

on: [pull_request]

jobs:
  lint:
    name: runner / lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node/npm
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: markdownlint-github-pr-review
        uses: reviewdog/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: 'articles/**'
